version: "3.9"
services:
  postgres:
    image: postgres:14.1
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: iniT11
      POSTGRES_USER: instabank
      POSTGRES_DB: instabank
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./mntdata:/var/lib/postgresql/data
      - ./workdir:/workdir
    working_dir: /workdir
  mock:
    image: ghcr.io/pivotal-gss/mock-data:latest
    volumes:
      - ./mock-data:/home/mock
