version: "3.9"
services:
  postgres:
    image: postgres:14.1
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
